# Define server port
server:
  port: 8800

# Setup connect database
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3360/spring_security?createDatabaseIfNotExist=true'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Environment Variables
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # HS256 Format
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days